name = "Mill"
uuid = "1d0525e4-8992-11e8-313c-e310e1f6ddea"
authors = ["Tomas Pevny <pevnak@protonmail.ch>", "Simon Mandlik <simon.mandlik@gmail.com>"]
version = "1.0.4"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Duff = "3e2ffa6a-ba38-11e8-0a1c-7b69309e1c72"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
LearnBase = "7f8f8fb0-2700-5f03-b4bd-41f8cfc144b6"
MLDataPattern = "9920b226-0b2a-5f5f-9153-9aa70a013f8b"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
Combinatorics = "≥ 0.7"
DataFrames = "≥ 0.19"
DataStructures = "≥ 0.17"
Duff = "≥ 0.4"
Flux = "≥ 0.10"
LearnBase = "≥ 0.2"
MLDataPattern = "≥ 0.5"
Zygote = "≥ 0.4"
julia = "≥ 1.3"
